services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    entrypoint: ./start_app.sh
    depends_on:
      - pgvector
      - redis
      - mongo
    environment:
      REDIS_HOST: redis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: pgvector
      POSTGRES_PORT: 5432
      POSTGRES_DB_NAME: MasterDB

  pgvector:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=MasterDB

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2.4-alpine

  celery-worker:
    build:
      dockerfile: Dockerfile
    entrypoint: ./start_celery_worker.sh
    depends_on:
      - app
      - redis
    environment:
      REDIS_HOST: redis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: pgvector
      POSTGRES_PORT: 5432
      POSTGRES_DB_NAME: MasterDB

  flower:
    build:
      dockerfile: Dockerfile
    entrypoint: ./start_celery_flower.sh
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery-worker
    environment:
      REDIS_HOST: redis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: pgvector
      POSTGRES_PORT: 5432
      POSTGRES_DB_NAME: MasterDB

volumes:
  postgres_data:
  mongo_data:
